# Site Settings
name: Zero a Hacking
title: Blog de Seguridad Informatica | Bienvenido
description: Este es un blog donde se hablaran temas de hacking & seguridad informatica.
tags:
  - zerosecinfo
  - alamillodiazdeleon
  - hacking
  - seguridadinformatica
  - ethicalhacking
email: alamillodiazdeleon@gmail.com
disqus_username: Astrax
show_hero: true
menu:
  - title: Inicio
    url: /
  - title: Acerca del autor
    url: /about
  - title: Contacto
    url: /contact
  - title: #Feed
    url: /feed.xml


# Social Media Settings
# Remove the item if you don't need it
github_username: astr4x
facebook_username: zerosecinfo
twitter_username: Astrax0
instagram_username: secalamillo/
linkedin_username: jose-angel-alamillo-diaz-de-leon-1584b1195/


# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: false


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "es"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: #v3.0.2
